### ISSUE TITLE
Ruby error after crane lift blog

### ISSUE THREAD

**Issue by zukko78** [michaelsauter/sinatra-crane-env#1]
Hi guys,

I have tryed to build images with crane but I faced next error:

libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)
        --with-atomic_reference-dir
        --without-atomic_reference-dir
        --with-atomic_reference-include
        --without-atomic_reference-include=${atomic_reference-dir}/include
        --with-atomic_reference-lib
        --without-atomic_reference-lib=${atomic_reference-dir}/lib
/usr/lib/ruby/2.2.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/lib/ruby/2.2.0/mkmf.rb:587:in`try_cpp'
        from /usr/lib/ruby/2.2.0/mkmf.rb:1060:in `block in have_header'
        from /usr/lib/ruby/2.2.0/mkmf.rb:911:in`block in checking_for'
        from /usr/lib/ruby/2.2.0/mkmf.rb:351:in `block (2 levels) in postpone'
        from /usr/lib/ruby/2.2.0/mkmf.rb:321:in`open'
        from /usr/lib/ruby/2.2.0/mkmf.rb:351:in `block in postpone'
        from /usr/lib/ruby/2.2.0/mkmf.rb:321:in`open'
        from /usr/lib/ruby/2.2.0/mkmf.rb:347:in `postpone'
        from /usr/lib/ruby/2.2.0/mkmf.rb:910:in`checking_for'
        from /usr/lib/ruby/2.2.0/mkmf.rb:1059:in `have_header'
        from extconf.rb:17:in`<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /blog/.bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/atomic-1.1.15/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /blog/.bundle/ruby/2.2.0/gems/atomic-1.1.15 for inspection.
Results logged to /blog/.bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0/atomic-1.1.15/gem_make.out
An error occurred while installing atomic (1.1.15), and Bundler cannot continue.
Make sure that `gem install atomic -v '1.1.15'` succeeds before bundling.
Could not find atomic-1.1.15 in any of the sources
Run `bundle install` to install missing gems.
/usr/local/bin/start-blog: line 4: rackup: not found
ERROR: exit status 127

Could you please clarify what can I do to fix this error. I have use Linux ubuntu 4.2.0-27-generic #32-Ubuntu and docker - Docker version 1.10.2, build c3959b1

**Comment by michaelsauter** [comment]
Hi there. Sorry I don't have the time to look into this right now. Must be some missing package in the image, probably due to a new dependency of Sinatra that wasn't present when I built this originally. You should be able to figure this out with googling, or just replace the base image with some other image that has the correct packages installed.
